[package]
name = "fastq"
version = "0.2.0"
authors = ["Adrian Seyboldt <adrian.seyboldt@gmail.com>"]
description = "A parser for fastq"
license = "MIT"
repository = "https://github.com/aseyboldt/fastq-rs"

[profile.release]
debug = true
opt-level = 3
debug-assertions = false

[dependencies]
memchr = ">=0.1"

[dev-dependencies]
parasailors = "^0.3"
lz4 = "^1.20"
