[package]
name = "fastq"
version = "0.2.0"
authors = ["Adrian Seyboldt <adrian.seyboldt@gmail.com>"]

[profile.release]
debug = true
opt-level = 3
debug-assertions = false

[dependencies]
memchr = ">=0.1"

[dev-dependencies]
parasailors = "*"
lz4 = "*"
