[package]
name = "fastq"
version = "0.1.0"
authors = ["Adrian Seyboldt <adrian.seyboldt@gmail.com>"]

[profile.release]
debug = false
panic = "abort"
opt-level = 3
lto = false
debug-assertions = false
codegen-units = 1

[dependencies]
bio = "*"
memchr = "*"
libc = { git = "file:///home/adr/git/libc" }
twoway = { version = "*", features = ["pcmp"]}
lz4 = { git = "file:///home/adr/git/lz4-rs" }
parasailors = "*"
